// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: timed.proto

package timed

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TimedGreeter_SayHello_FullMethodName = "/timed.TimedGreeter/SayHello"
)

// TimedGreeterClient is the client API for TimedGreeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TimedGreeterClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type timedGreeterClient struct {
	cc grpc.ClientConnInterface
}

func NewTimedGreeterClient(cc grpc.ClientConnInterface) TimedGreeterClient {
	return &timedGreeterClient{cc}
}

func (c *timedGreeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, TimedGreeter_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimedGreeterServer is the server API for TimedGreeter service.
// All implementations must embed UnimplementedTimedGreeterServer
// for forward compatibility.
type TimedGreeterServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedTimedGreeterServer()
}

// UnimplementedTimedGreeterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTimedGreeterServer struct{}

func (UnimplementedTimedGreeterServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedTimedGreeterServer) mustEmbedUnimplementedTimedGreeterServer() {}
func (UnimplementedTimedGreeterServer) testEmbeddedByValue()                      {}

// UnsafeTimedGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimedGreeterServer will
// result in compilation errors.
type UnsafeTimedGreeterServer interface {
	mustEmbedUnimplementedTimedGreeterServer()
}

func RegisterTimedGreeterServer(s grpc.ServiceRegistrar, srv TimedGreeterServer) {
	// If the following call pancis, it indicates UnimplementedTimedGreeterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TimedGreeter_ServiceDesc, srv)
}

func _TimedGreeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimedGreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimedGreeter_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimedGreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TimedGreeter_ServiceDesc is the grpc.ServiceDesc for TimedGreeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TimedGreeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "timed.TimedGreeter",
	HandlerType: (*TimedGreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _TimedGreeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "timed.proto",
}
